steps:
    # Build
    - name: 'docker'
      args: ['build', '-t', 'app', '.']

    - name: 'docker'
      args: ['run', 'app', 'python3', 'manage.py', 'migrate']

    # Test
    - name: 'docker'
      args: ['run', 'app', 'python3', 'manage.py', 'test']